### ISSUE TITLE
[Create] FormPatient Component

### ISSUE THREAD

**Issue by aherreDev** [xErikPsx/balto-front#9]

**Comment by JonathanSolisCeballos** [comment]
- Estatus del paciente [sin cambios, mejorando, empeorando, fallecido].
- Nombres, 
- Apellidos, 
- Género, 
- Edad
- Foto
- Estado Civil
- Nacionalidad
- Estado del país
- Alergias
- Tipo de sangre
- Estatura
- Peso
- Dirección
- Teléfono
- Nombre Completo de familiar
- Dirección de familiar
- Teléfono de familiar
- Nombre del Doctor asignado
- Síntomas [fiebre, tos seca, congestión nasal, dolor de garganta, secreción nasal, dificultad para respirar, fatiga, dolor de cabeza, diarrea]
-
